pipeline {
    agent any

    environment {
        REGISTRY = "192.168.0.112:5000"
        IMAGE_NAME = "jenkins-hello"
    }

    stages {
        stage('Clone') {
            steps {
                echo "Repo cloned automatically by Jenkins"
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('docker-apps/hello-jenkins') {
                    sh 'docker build -t $REGISTRY/$IMAGE_NAME .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'nexus-docker-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login $REGISTRY -u "$DOCKER_USER" --password-stdin
                        docker push $REGISTRY/$IMAGE_NAME
                    '''
                }
            }
        }
        
        stage('Deploy Docker Image') {
          steps {
            dir('docker-apps/hello-jenkins') {
              sh 'docker-compose down || true'
              sh 'docker-compose pull'
              sh 'docker-compose up -d'
            }
          }
        }
    }
}
