pipeline {
    agent any

    environment {
        REGISTRY = "192.168.0.112:5000"
        IMAGE_NAME = "jenkins-hello"
    }

    stages {
        stage('Clone') {
            steps {
                echo "Repo cloned automatically by Jenkins"
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('docker-apps/hello-jenkins') {
                    sh 'docker build -t $REGISTRY/$IMAGE_NAME .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push $REGISTRY/$IMAGE_NAME'
            }
        }
    }
}
