pipeline {
  agent any

  environment {
    IMAGE_NAME = "192.168.0.112:5000/jenkins-hello"
  }

  stages {
    stage('Clone') {
      steps {
        echo 'Repo cloned automatically by Jenkins'
      }
    }

    stage('Build Docker Image') {
      steps {
        dir('devops-stack/jenkins') {
          sh 'docker build -t $IMAGE_NAME .'
        }
      }
    }

    stage('Push Docker Image') {
      steps {
        sh 'docker push $IMAGE_NAME'
      }
    }
  }
}
