# ~/ansible/roles/docker-install/tasks/main.yml

- name: Install dependencies
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release']
    state: present
    update_cache: true

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Add current user to docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started
